### ISSUE TITLE
version tag does not fit build.gradle version

### ISSUE THREAD

**Issue by theScrabi** [PuffOpenSource/Puff-Android#1]
Tha last taged version was [v.0.9](https://github.com/PuffOpenSource/Puff-Android/releases/tag/v0.9) but in the build.gradle file it says [1.0](https://github.com/PuffOpenSource/Puff-Android/blob/master/app/build.gradle#L12). In order to release this app on [fdroid](https://f-droid.org/) you have to fix this, and make your tag also a 1.0

**Comment by SpongeBobSun** [comment]
@theScrabi Fixed. Changed release tag to 1.0

Could you please leave a message on this issue when this app is released to fdroid? Thanks.

**Comment by theScrabi** [comment]
The app was merged, but I'm wondering why it's not appearing in the list.

**Comment by SpongeBobSun** [comment]
@theScrabi Beats me too... Anyway I'll keep an eye on it. 

BTW will f-droid automatically build my new version when I pushed a new release ? Or I need raise a pull request manually ?

**Comment by theScrabi** [comment]
Every tag will will be build by fdroid.
