### ISSUE TITLE
Export database fails

### ISSUE THREAD

**Issue by coldcode69** [PuffOpenSource/Puff-Android#13]
I have tried exporting the database a few times and it always gives me a message saying "Failed! Please try again.".

I'm running Android 6.0.1

**Comment by SpongeBobSun** [comment]
Did you granted `external storage` permission to Puff?

**Comment by coldcode69** [comment]
That fixed it. 

I normally get a pop-up asking me to give the permission so didn't even consider this. Thanks anyway!
