### ISSUE TITLE
主密码输入次数能否降低？

### ISSUE THREAD

**Issue by ATLgo** [PuffOpenSource/Puff-Android#8]
看到这款软件，觉得颜值很高，使用了一下，软件逻辑都比较舒适，感谢作者的应用。

几乎所有的操作都需要输入主密码，建议更改为，从进入软件界面到退出当前界面(或切换到其他界面)只需要输入一次主密码。

**Comment by SpongeBobSun** [comment]
Nope. Because I don't save the main password directly. And I don't think there is a safe place to save it on Android. 

You can enable gesture lock in the settings page.

Thanks for the advice.

**Comment by ATLgo** [comment]
OK, Good feature.
